### ISSUE TITLE
Using CRS from `to_cartopy_crs()` triggers AttributeError in shapely

### ISSUE THREAD

**Issue by gerritholl** [pytroll/pyresample#297]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
import pyresample
import matplotlib.pyplot
import PIL.Image
import cartopy.crs
ar = pyresample.create_area_def(
            "fribbulus xax",
            {"proj": "eqc", "ellps": "WGS84", "units": "m"},
            resolution=3000,
            area_extent=[-9163411, 4255208, -7369792, 5424479])
crs = ar.to_cartopy_crs()
# crs = cartopy.crs.PlateCarree()
f = matplotlib.pyplot.figure()
f.add_subplot(1, 1, 1, projection=crs)
f.axes[0].coastlines()
f.axes[0].gridlines()
pim = PIL.Image.new("LA", (2, 2))
f.axes[0].imshow(pim)
f.canvas.print_figure("/tmp/fubar.png")

```
#### Problem description

When I use a CRS obtained from pyresample's `.to_cartopy_crs()`, and then use both `.coastlines()` and `.imshow()` in the corresponding `GeoAxesSubplot()`, then attempting to show or print the figure results in an `AttributeError` from shapely.  This problem does not occur with a builtin cartopy CRS, nor when I use only one of `.coastlines()` or `.imshow()`.

#### Expected Output

I expect the image and coastlines to be both displayed in the `GeoAxesSubplot`, without an exception to be raised.

#### Actual Result, Traceback if applicable

```
WARNING:root:shape found from radius and resolution does not contain only integers: (389.757, 597.873)
Rounding shape to (390, 598) and resolution from (3000.0, 3000.0) meters to (2999.3628762541807, 2998.130769230769) meters
/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/pyresample/utils/cartopy.py:65: UserWarning: Converting EPSG projection to proj4 string, which is a potentially lossy transformation                                                                                        
  warnings.warn('Converting EPSG projection to proj4 string, which is a potentially lossy transformation')
Traceback (most recent call last):
  File "mwe85.py", line 18, in <module>
    f.canvas.print_figure("/tmp/fubar.png")
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    FigureCanvasAgg.draw(self)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/matplotlib/figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 479, in draw
    return matplotlib.axes.Axes.draw(self, renderer=renderer, **kwargs)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2748, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    extent = ax.get_extent(feature_crs)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 730, in get_extent
    p = self._get_extent_geom(crs)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 775, in _get_extent_geom
    geom_in_crs = proj.project_geometry(geom_in_src_proj,
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/cartopy/crs.py", line 218, in project_geometry
    return getattr(self, method_name)(geometry, src_crs)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/cartopy/crs.py", line 354, in _project_polygon
    is_ccw = polygon.exterior.is_ccw
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/shapely/geometry/polygon.py", line 88, in is_ccw
    return bool(self.impl['is_ccw'](self))
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/shapely/algorithms/cga.py", line 14, in is_ccw_op
    return signed_area(ring) >= 0.0
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/shapely/algorithms/cga.py", line 6, in signed_area
    xs, ys = ring.coords.xy
AttributeError: 'list' object has no attribute 'xy'
```

#### Versions of Python, package at hand and relevant dependencies

* cartopy 0.18.0
* matplotlib 3.3.1
* pyresample 1.16.0+7.gfc78bda
* python 3.8.5
* shapely 1.7.1

**Comment by gerritholl** [comment]
I don't know whether this problem lies with pyresample, matplotlib, cartopy, shapely, proj4, with me, or somewhere else altogether.

**Comment by djhoese** [comment]
Have you tried downgrading cartopy and *maybe* shapely?

**Comment by djhoese** [comment]
Possibly related: https://github.com/Toblerity/Shapely/issues/959

**Comment by gerritholl** [comment]
I'll try some different combinations in a clean conda environment.

**Comment by gerritholl** [comment]
I get a _different_ traceback with cartopy 0.17.0, shapely 1.6.4:

```
Traceback (most recent call last):
  File "mwe85.py", line 18, in <module>
    f.canvas.print_figure("/tmp/fubar.png")
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    FigureCanvasAgg.draw(self)
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/matplotlib/figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 387, in draw
    return matplotlib.axes.Axes.draw(self, renderer=renderer,
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2748, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/cartopy/mpl/feature_artist.py", line 161, in draw
    extent = ax.get_extent(feature_crs)
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 600, in get_extent
    p = self._get_extent_geom(crs)
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 645, in _get_extent_geom
    geom_in_crs = proj.project_geometry(geom_in_src_proj,
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/cartopy/crs.py", line 218, in project_geometry
    return getattr(self, method_name)(geometry, src_crs)
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/cartopy/crs.py", line 354, in _project_polygon
    is_ccw = polygon.exterior.is_ccw
AttributeError: 'NoneType' object has no attribute 'is_ccw'
```

**Comment by djhoese** [comment]
Try shapely 1.7.0. Just curious based on the commit history I'm seeing.

**Comment by gerritholl** [comment]
I don't find any combination that doesn't have either this error or another error.  Summary from various combinations of versions, every time installed in a newly created conda environment:

Using cartopy 0.18.0 or 0.17.0 with shapely 1.7.0 or 1.7.1:  `AttributeError` from shapely..algorithms.cga, see top comment.

Using cartopy 0.17.0 with shapely 1.6.4:  `AttributeError` from `cartopy.crs` (see previous comment).

Using cartopy 0.18.0 with shapely 1.6.4:

```
Traceback (most recent call last):
  File "mwe85.py", line 4, in <module>
    import cartopy.crs
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/cartopy/__init__.py", line 96, in <module>
    import cartopy.crs
  File "/data/gholl/miniconda3/envs/exp/lib/python3.8/site-packages/cartopy/crs.py", line 36, in <module>
    from cartopy._crs import (CRS, Geodetic, Globe, PROJ4_VERSION,
ImportError: libproj.so.19: cannot open shared object file: No such file or directory
```

I can't seem to install cartopy 0.16 or shapely 1.5, they're too old for Python 3.8 (conda conflicts and shapely 1.5 only up to Python 3.6).

NB: when I upgrade from shapely 0.16.4 to 0.17.0, conda needs to install a LOT of new packages.  When I downgrade from 0.17.0 to 0.16.4, it reports that it has found conflicts.

**Comment by djhoese** [comment]
Cartopy 0.18.0, shapely 1.7.0, and python 3.7 work for me on PopOS (Ubuntu based).

**Comment by gerritholl** [comment]
I still get the same exception with Python 3.7, shapely 1.7.0, cartopy 0.18.0 on openSUSE 15.0.

**Comment by djhoese** [comment]
```(satpy_py37) davidh@janet:/tmp$ conda list proj
# packages in environment at /home/davidh/miniconda3/envs/satpy_py37:
#
# Name                    Version                   Build  Channel
proj                      7.0.0                h966b41f_3    conda-forge
pyproj                    2.6.0            py37h34dd122_1    conda-forge```

**Comment by gerritholl** [comment]
I just downgraded to those exact versions of proj and pyproj, but still the same `AttributeError` from `shapely`.

**Comment by gerritholl** [comment]
I have a `libproj.so.19.0.0` in the `lib/` directory in my conda environment, but I don't know what package installed it as my version of proj is `7.0.0`.

**Comment by gerritholl** [comment]
Ah, despite the different version numbers that file comes from proj, as revealed by `grep libproj /data/gholl/miniconda3/envs/exp/conda-meta/proj-7.0.0-h966b41f_5.json`.  Then where else may my system differ?

I will try installing it all on a couple of different machines for comparison.

**Comment by gerritholl** [comment]
I get the same on a different machine running CentOS Linux release 7.6.1810.

**Comment by gerritholl** [comment]
@djhoese  I just fixed an error in the MCVE.  The line `f.axes[0].imshow(pim)` was commented out, but should be included as regular code for the problem to occur.

**Comment by djhoese** [comment]
Ah there we go, now I get the exception.

**Comment by gerritholl** [comment]
Any clue if this is a problem in pyresample or something in one of the dependencies?

**Comment by djhoese** [comment]
I think this may be a problem with your usage...try this example which I took from your example and compared it to my half day tutorial example:

```
import pyresample
import matplotlib.pyplot as plt
import PIL.Image
import cartopy.crs
ar = pyresample.create_area_def(
            "fribbulus xax",
            {"proj": "eqc", "ellps": "WGS84", "units": "m"},
            resolution=3000,
            area_extent=[-9163411, 4255208, -7369792, 5424479])
crs = ar.to_cartopy_crs()
plt.figure()
ax = plt.axes(projection=crs)
ax.coastlines()
ax.gridlines()
plt.show()
```

**Comment by djhoese** [comment]
I'm not realizing this is likely because of an interaction with the `imshow` which you already pointed out was needed to make it fail. :facepalm:

**Comment by djhoese** [comment]
Ok so I'm not sure how this used to perform but I've been playing around with this bit of code:

https://github.com/SciTools/cartopy/blob/master/lib/cartopy/mpl/geoaxes.py#L800-L808

The issue comes from the coastlines being in PlateCaree and cartopy is trying to find where the boundaries of their CRS intersects with our custom CRS. It is resulting in no intersection which results in an empty polygon which then shows up as the error you originally saw. So the next question is why doesn't showing the coastlines by themselves (no imshow) show this issue?

**Comment by gerritholl** [comment]
Why is there no intersection with the custom CRS?

**Comment by djhoese** [comment]
The computed bounds for the view seem to be messed up. I was able to get data on the screen with coastlines by doing:

```
In [79]: f = plt.figure()

In [80]: ax = f.add_subplot(1, 1, 1, projection=crs)

In [81]: img = ax.imshow(data, transform=crs, extent=crs.bounds)

In [82]: cl = ax.coastlines()

In [83]: f.show()
```

**Comment by djhoese** [comment]
Without forcing the extent on the imshow, it seems that `_get_extent_geom` is being told that the limits of the plot/axes are:

```
-7369792.0 -0.5 4255208.0 199.5
```

where that's xmin, xmax, ymin, ymax. Clearly the ymin/max are flipped but that doesn't seem to change anything if you flip them. The big problem I think is the xmin/xmax since our CRS's x-limits are actually `-9163411.0 -7369792.0`. So for some reason the plot thinks the data should be on the right of our CRS, hence not *in* our CRS.

**Comment by djhoese** [comment]
Closest thing I can find that might be the problem is https://github.com/SciTools/cartopy/commit/9c418ef8142a91561f9b21288c92653a74e55af8#diff-b599a1ae2427ad1c63351afff7e4e9c5

**Comment by djhoese** [comment]
So I think the bug here is in the usage you have. I'm able to follow my tutorial and get plots out as expected: https://github.com/pytroll/tutorial-satpy-half-day/blob/adfa08c7458ebf09e7a8c0148118afcfb2176c95/notebooks/07_cartopy_geoviews.ipynb

There is some weirdness with the limits that cartopy/matplotlib is computing, but that is mainly because it doesn't know where your image is supposed to go relative to the plot. Since you aren't telling it the extents of the image it defaults to putting the image at coordinates [0, 200] (for a 200 pixel image, I was doing `np.random.random`).

So there are bugs somewhere in shapely when a Polygon is empty/no area, but I think that can be worked around and is already a known issue on shapely's side. There may be a bug in matplotlib with how it is computing limits, but I'm not sure exactly what I would expect in this case either.

As a workaround I think you can either set your axes limits before showing (`ax.set_xlim`, etc) or specify the extent of the image when you call `imshow`. I think either works. Also note I was providing the crs to my `imshow` but I think the default for GeoAxes is to do that anyway.

**Comment by gerritholl** [comment]
Although it got lost in the MCVE, in my original use case I got the image via `get_enhanced_image`, so then it should be geolocated already...

**Comment by djhoese** [comment]
But `get_enhanced_image` is only returning a numpy array (or is it an XRImage). Regardless, you haven't told matplotlib anything about that geolocation information unless you explicitly tell it the CRS and the extent of the image array you're passing to imshow.

**Comment by gerritholl** [comment]
It returns an `XRImage`, which I thought carried geolocation information in its headers.  But maybe not in a way cartopy understands, so I guess the problem is indeed on my side.

**Comment by djhoese** [comment]
An `XRImage` is a trollimage object which contains an xarray `DataArray` (under `.data` iirc). This `DataArray`, when coming from Satpy, should include a `.attrs['area']` object which could be converted to a Cartopy CRS but that requires you to do the conversion.  This area attribute is only known to pytroll tools and is not currently handled by any other library including xarray and cartopy so it is up to you to convert to a cartopy CRS object and provide it to imshow. Sorry for the confusion.
